name: Follow
main: com.yayestechlab.minecraft.Follow.Main
version: 0.1
commands:
    follow:
        description: This is a demo command.
        usage: /<command>
        permission: follow.follow
        permission-message: You dont have permission!
permissions:
    follow.follow:
        description: Allows you to follow other players
        default: op
